### ISSUE TITLE
Export fails

### ISSUE THREAD

**Issue by kyla-mcconnell** [zrrrzzt/b5-web#152]
The exporting to a serverless folder fails with the following error:
```
Error: Cannot export when target is not server. https://err.sh/zeit/next.js/next-export-serverless
    at _default (/home/ubuntu/server/jspsych_Big5/node_modules/next/dist/export/index.js:1:3018)
    at nextExport (/home/ubuntu/server/jspsych_Big5/node_modules/next/dist/cli/next-export.js:20:325)
    at commands.(anonymous function).then.exec (/home/ubuntu/server/jspsych_Big5/node_modules/next/dist/bin/next:29:346)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```
I'm using the latest npm on Ubuntu 16.04.

**Comment by zrrrzzt** [comment]
You'll have to change the `target` to 'server' in the `next.config.js`file to export to static files.

I have update the README. Sorry for the inconvenience.

**Comment by kyla-mcconnell** [comment]
Thank you! Now, the exporting works but the buttons on the index.html don't do anything. Why might this be?

**Comment by zrrrzzt** [comment]
Strange! I'll look into it. Ive only used the `ZEIT/Now` myself.

**Comment by zrrrzzt** [comment]
So I just tried `npm run export && npx serve dist` to export the module and start a local webserver with `serve`. Everything worked as expected. What kind of server are you running when it fails?
